name: Deployment
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deployment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v7
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist/
            package.json
      - name: check lints
        run: npm run lint
      - name: Deploy
        run: echo "deploying"



    